using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using ShopEazy.Client;
using Syncfusion.Blazor;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("Mgo+DSMBaFt/QHJqVVhjWlpFdEBBXHxAd1p/VWJYdVt5flBPcDwsT3RfQF9jQXxbdkNjWHxedHJXQA==;Mgo+DSMBPh8sVXJ0S0R+XE9HcFRDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS3xTfkdrWXlecXdVQmdZVw==;ORg4AjUWIQA/Gnt2VVhiQlFadVlJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxRdk1hUX9YcHVWRmRUVkI=;NzA1NjgzQDMyMzAyZTMyMmUzME50MWkyZERJWXlvdDJYVVJndi92Q01PN0Njd2JweDhLeE04L0tRR2NwUE09;NzA1Njg0QDMyMzAyZTMyMmUzME1JMjNSN2ttSzRyeW9tS1VIYkYrRllkT1RtNEN0RVkrdDRYRExvNU5EcjA9;NRAiBiAaIQQuGjN/V0Z+Xk9EaFxEVmJLYVB3WmpQdldgdVRMZVVbQX9PIiBoS35RdEVrW3dednRURWBZVEdw;NzA1Njg2QDMyMzAyZTMyMmUzMEFOaUdCYUVrTVhNRHJ5WDc3Vis5Vjc4L3pTamo3SEk1YWE3NFZ1bjEwZ1U9;NzA1Njg3QDMyMzAyZTMyMmUzMGxIdkdpdXB1TEcxTmx5Z2hJV0ZELzRmUXA3SElqSG8vRDhzcUtXbXZDbkE9;Mgo+DSMBMAY9C3t2VVhiQlFadVlJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxRdk1hUX9YcHVWRmZeVkI=;NzA1Njg5QDMyMzAyZTMyMmUzMEU1N1FhV0tvQ2FZaGpMWm5pd2FielJQczJyTm4ycCt3M1diVmVHazB2bjA9;NzA1NjkwQDMyMzAyZTMyMmUzMGwvTEpsZjJ3YVV5TEUyRGVvTHZBY0doNlhLRnI3dHY3bzcybkwwbXVrOXc9;NzA1NjkxQDMyMzAyZTMyMmUzMEFOaUdCYUVrTVhNRHJ5WDc3Vis5Vjc4L3pTamo3SEk1YWE3NFZ1bjEwZ1U9");
builder.Services.AddSyncfusionBlazor();
await builder.Build().RunAsync();
